import { Card, CardContent } from "./components/ui/card"
import { motion } from "framer-motion"
import { Github, Linkedin, Mail, BookOpen } from "lucide-react"

export default function Portfolio() {
  return (
    <div className="min-h-screen bg-white text-gray-900 font-sans">
      {/* Header Section */}
      <header className="text-center py-16">
        <div className="flex flex-col items-center mb-6">
          <div className="w-32 h-32 rounded-full bg-gray-200 mb-4 overflow-hidden">
            {/* Placeholder for profile picture */}
            <img src="https://media.licdn.com/dms/image/v2/D5603AQE-Tx8FPb7k-w/profile-displayphoto-shrink_200_200/B56ZTcYy53HsAg-/0/1738864275501?e=1764201600&v=beta&t=AcY8yp4MB_3CyD5Zq9IeFKd6BnKjWiUUr8M56y_aOHE" alt="Profile placeholder" className="w-full h-full object-cover" />
          </div>
        </div>
        <motion.h1 initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="text-5xl font-semibold mb-2">
          Shaghayegh Sadeghi
        </motion.h1>
        <p className="text-base text-gray-700">Postdoctoral Fellow, Future Cities Institute — University of Waterloo</p>
        <p className="text-sm text-gray-500 mb-6">Ph.D. in Computer Science — University of Windsor</p>
        <div className="flex justify-center space-x-5">
          <a href="https://github.com/sshaghayeghs" target="_blank" rel="noopener noreferrer"><Github className="w-5 h-5 hover:text-gray-600 transition-colors" /></a>
          <a href="https://www.linkedin.com/in/shaghayegh-sadeghi-a0460612b/" target="_blank" rel="noopener noreferrer"><Linkedin className="w-5 h-5 hover:text-gray-600 transition-colors" /></a>
          <a href="mailto:shaysadeghi93@gmail.com"><Mail className="w-5 h-5 hover:text-gray-600 transition-colors" /></a>
          <a href="https://scholar.google.ca/citations?user=gif2gGEAAAAJ&hl=en" target="_blank" rel="noopener noreferrer"><BookOpen className="w-5 h-5 hover:text-gray-600 transition-colors" /></a>
        </div>
      </header>

      {/* About Section */}
      <section className="max-w-3xl mx-auto px-4 text-center py-10">
        <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.8 }} className="text-lg text-gray-800 leading-relaxed">
          I am a Machine Learning Research Scientist and Postdoctoral Fellow focused on AI, NLP, and urban optimization.
          My research centers on large language models, graph neural networks, and representation learning for smart city systems.
        </motion.p>
      </section>

      {/* Research Section */}
      <section className="max-w-5xl mx-auto px-4 py-16">
        <h2 className="text-2xl font-semibold text-center mb-10">Research Highlights</h2>
        <div className="grid md:grid-cols-3 gap-8">
          {[{
            title: "MolEval: Molecular Embedding Evaluation Toolkit",
            desc: "Benchmarks molecular embeddings generated by LLMs against specialized models.",
            link: "https://github.com/sshaghayeghs/MolEval"
          }, {
            title: "SentEval+: Post-Processing Toolkit for LLMs",
            desc: "Evaluates whitening and alignment methods for sentence embeddings.",
            link: "https://github.com/sshaghayeghs/senteval-plus"
          }, {
            title: "LLMs for Molecular Understanding",
            desc: "Investigated how LLMs interpret molecular structures for property prediction.",
            link: "https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-024-05847-x"
          }].map((project, i) => (
            <motion.div key={i} whileHover={{ scale: 1.02 }}>
              <Card className="border border-gray-200 shadow-sm bg-white rounded-xl transition-transform">
                <CardContent className="p-5">
                  <h3 className="font-medium text-lg mb-2 text-gray-900">{project.title}</h3>
                  <p className="text-gray-600 text-sm mb-4">{project.desc}</p>
                  <a href={project.link} target="_blank" rel="noopener noreferrer" className="text-sm text-gray-700 hover:text-black underline">
                    View Project
                  </a>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Publications */}
      <section className="max-w-4xl mx-auto px-4 py-10">
        <h2 className="text-2xl font-semibold text-center mb-6">Selected Publications</h2>
        <ul className="space-y-3 text-gray-700 text-base">
          <li><strong>Can Large Language Models Understand Molecules?</strong> — BMC Bioinformatics, 2024</li>
          <li><strong>MolEval:</strong> ICML Workshop, 2024</li>
          <li><strong>Whitening Not Recommended for Classification Tasks:</strong> ACL Workshop, 2024</li>
        </ul>
      </section>

      {/* Contact */}
      <footer className="text-center py-10 border-t border-gray-200">
        <h3 className="text-xl font-medium mb-2">Get in Touch</h3>
        <p className="text-gray-600 mb-4">Open to collaborations, speaking opportunities, and research discussions.</p>
        <a href="mailto:shaysadeghi93@gmail.com" className="text-sm text-gray-700 underline hover:text-black">
          shaysadeghi93@gmail.com
        </a>
        <p className="mt-6 text-xs text-gray-500">© 2025 Shaghayegh Sadeghi</p>
      </footer>
    </div>
  )
}
